spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
    locations: classpath:db/migration
  jackson:
    date-format: dd-MM-yyyy HH:mm
    time-zone: UTC

security:
  jwt:
    secret: c2ZBJUAjZndFZ2Yyd21uZm9qMTIzb2pmOGozNTFoZm5xMjNuZjkx
    access: 3600000
    refresh: 2592000000