spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 10.182.81.177
      port: 6379

  flyway:
    enabled: false
    locations: classpath:db/migration
  jackson:
    date-format: dd-MM-yyyy HH:mm
    time-zone: UTC
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


security:
  jwt:
    secret: c2ZBJUAjZndFZ2Yyd21uZm9qMTIzb2pmOGozNTFoZm5xMjNuZjkx
    access: 3600000
    refresh: 2592000000

minio:
  url: http://10.182.81.177:9003
#  url: http://minio:9003
#  url: http://localhost:9003
  accessKey: admin
  secretKey: admin1234
  bucket: avatars
